apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: inevitable-duck-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inevitable-duck-go 
  name: inevitable-duck-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: inevitable-duck-go
    weight: 100 
