apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: inevitable-duck-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inevitable-duck-go 
  name: inevitable-duck-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: inevitable-duck-go 
